export const THEMES = {
  SUPERADMIN: {
    nav:         'bg-gray-950 border-gray-800',
    navText:     'text-gray-100',
    navSub:      'text-gray-400',
    navBadge:    'bg-purple-600 text-white',
    sidebar:     'bg-gray-900 border-gray-800',
    sidebarText: 'text-gray-300',
    sidebarHover:'hover:bg-gray-800 hover:text-white',
    sidebarActive:'bg-gray-700 text-white',
    sidebarLabel:'text-gray-500',
    accent:      'bg-purple-600',
    accentText:  'text-purple-400',
    dot:         'bg-purple-500',
    border:      'border-gray-800',
  },
  ADMIN: {
    nav:         'bg-red-950 border-red-900',
    navText:     'text-red-50',
    navSub:      'text-red-300',
    navBadge:    'bg-red-700 text-white',
    sidebar:     'bg-red-950 border-red-900',
    sidebarText: 'text-red-200',
    sidebarHover:'hover:bg-red-900 hover:text-white',
    sidebarActive:'bg-red-800 text-white',
    sidebarLabel:'text-red-700',
    accent:      'bg-red-700',
    accentText:  'text-red-400',
    dot:         'bg-red-500',
    border:      'border-red-900',
  },
  USER: {
    nav:         'bg-blue-900 border-blue-800',
    navText:     'text-blue-50',
    navSub:      'text-blue-300',
    navBadge:    'bg-blue-600 text-white',
    sidebar:     'bg-blue-950 border-blue-900',
    sidebarText: 'text-blue-200',
    sidebarHover:'hover:bg-blue-900 hover:text-white',
    sidebarActive:'bg-blue-700 text-white',
    sidebarLabel:'text-blue-700',
    accent:      'bg-blue-600',
    accentText:  'text-blue-400',
    dot:         'bg-blue-400',
    border:      'border-blue-900',
  },
}

export const getTheme = (userType) => THEMES[userType] || THEMES.USER